import type { DeckSnapshot, Slide } from '@nodeslide/contracts';
import { useId } from 'react';
import type { KeyboardEvent as ReactKeyboardEvent } from 'react';

export interface UseNodeSlideDeckNavigationInput {
  snapshot: DeckSnapshot;
  activeSlideId: string;
  onActiveSlideChange?: ((slideId: string) => void) | undefined;
  /** Lets the styled host implement focus without a DOM query in this package. */
  onFocusRequest?: ((slideId: string) => void) | undefined;
  /** Optional host-provided panel ID. A React-stable ID is generated by default. */
  panelId?: string | undefined;
}

export interface NodeSlideSlideTabProps {
  'aria-controls': string;
  'aria-selected': boolean;
  'data-nodeslide-slide-tab': string;
  onClick: () => void;
  onKeyDown: (event: ReactKeyboardEvent<HTMLButtonElement>) => void;
  role: 'tab';
  tabIndex: 0 | -1;
}

export interface NodeSlideSlidePanelProps {
  id: string;
  role: 'tabpanel';
}

export interface NodeSlideDeckNavigation {
  orderedSlides: readonly Slide[];
  activeSlide: Slide | null;
  activeIndex: number;
  panelId: string;
  canNavigate: boolean;
  previous: () => void;
  next: () => void;
  getTabProps: (slideId: string) => NodeSlideSlideTabProps;
  getPanelProps: () => NodeSlideSlidePanelProps;
}

/**
 * Controlled deck-navigation state and accessible tab props without rendering
 * or querying host DOM. Invalid active IDs fail closed for relative movement.
 */
export function useNodeSlideDeckNavigation({
  snapshot,
  activeSlideId,
  onActiveSlideChange,
  onFocusRequest,
  panelId: hostPanelId,
}: UseNodeSlideDeckNavigationInput): NodeSlideDeckNavigation {
  const generatedPanelId = `nodeslide-panel-${useId().replaceAll(':', '')}`;
  const panelId = hostPanelId ?? generatedPanelId;
  const orderedSlides = snapshot.deck.slideOrder
    .map((slideId) => snapshot.slides.find((slide) => slide.id === slideId))
    .filter((slide): slide is Slide => slide !== undefined);
  const activeIndex = orderedSlides.findIndex((slide) => slide.id === activeSlideId);
  const activeSlide = activeIndex >= 0 ? (orderedSlides[activeIndex] ?? null) : null;
  const recoveryTabId = activeSlide === null ? orderedSlides[0]?.id : undefined;

  function selectRelative(offset: number): void {
    if (!onActiveSlideChange || activeIndex < 0 || orderedSlides.length < 2) return;
    const targetIndex = (activeIndex + offset + orderedSlides.length) % orderedSlides.length;
    const target = orderedSlides[targetIndex];
    if (target) onActiveSlideChange(target.id);
  }

  function selectFromTab(slideId: string, requestFocus: boolean): void {
    if (!onActiveSlideChange || !orderedSlides.some((slide) => slide.id === slideId)) return;
    onActiveSlideChange(slideId);
    if (requestFocus) onFocusRequest?.(slideId);
  }

  function getTabProps(slideId: string): NodeSlideSlideTabProps {
    return {
      'aria-controls': panelId,
      'aria-selected': slideId === activeSlideId,
      'data-nodeslide-slide-tab': slideId,
      onClick: () => selectFromTab(slideId, false),
      onKeyDown: (event) => {
        if (!onActiveSlideChange) return;
        const currentIndex = orderedSlides.findIndex((slide) => slide.id === slideId);
        if (currentIndex < 0 || orderedSlides.length === 0) return;
        const targetIndex = targetIndexForKey(event.key, currentIndex, orderedSlides.length);
        if (targetIndex === null) return;
        const target = orderedSlides[targetIndex];
        if (!target) return;
        event.preventDefault();
        selectFromTab(target.id, true);
      },
      role: 'tab',
      tabIndex: slideId === activeSlideId || slideId === recoveryTabId ? 0 : -1,
    };
  }

  return {
    orderedSlides,
    activeSlide,
    activeIndex,
    panelId,
    canNavigate: activeSlide !== null && orderedSlides.length >= 2 && !!onActiveSlideChange,
    previous: () => selectRelative(-1),
    next: () => selectRelative(1),
    getTabProps,
    getPanelProps: () => ({ id: panelId, role: 'tabpanel' }),
  };
}

function targetIndexForKey(key: string, currentIndex: number, length: number): number | null {
  if (currentIndex < 0 || length === 0) return null;
  if (key === 'ArrowRight' || key === 'ArrowDown') return (currentIndex + 1) % length;
  if (key === 'ArrowLeft' || key === 'ArrowUp') return (currentIndex - 1 + length) % length;
  if (key === 'Home') return 0;
  if (key === 'End') return length - 1;
  return null;
}
